export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  git fasd command-not-found
)

source $ZSH/oh-my-zsh.sh


tmux
# Customize
for config_file ($HOME/.dotfiles/zsh/*.zsh) source $config_file
